[build]
rustflags = [
  "-C", "link-self-contained=no",
  "-C", "link-arg=--initial-memory=65536",
  "-C", "link-arg=-zstack-size=128",
  "-C", "link-arg=--export=__heap_base",
  "-C", "link-arg=--export=__data_end",
  "-C", "link-args=--no-entry",
]
