/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only intended for use with Renesas products.
* No other uses are authorized. This software is owned by Renesas Electronics Corporation and is protected under all
* applicable laws, including copyright laws. 
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING THIS SOFTWARE, WHETHER EXPRESS, IMPLIED
* OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
* NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY
* LAW, NEITHER RENESAS ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE FOR ANY DIRECT,
* INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR
* ITS AFFILIATES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software and to discontinue the availability 
* of this software. By using this software, you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2024 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
*  File Name    : R9A02G021_WAMR_Interp_Fast_Mini.c
*  Description  : Main Program
*  Creation Date: 2025-02-15
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"
#include <stdio.h>
#include <stdint.h>

#include "bh_platform.h"
#include "wasm_export.h"

// Result: can print output but stop with error "Cannot access memory at address 0x1845c"
//#include "../../wasm_applications/helloworld-c/helloworld_wasm.h"

//Result: OK
//#include "../../wasm_applications/helloworld-rust/helloworld_wasm_cargo.h"

//Result:
#include "../../wasm_applications/helloworld-rust/helloworld_wasm_rusct.h"

int main(void);

const char *pixel = "FF0000";

static void wasm_os_printf(wasm_exec_env_t exec_env, const char *message) {
    os_printf("%s", message);
}

static void *
app_instance_main(wasm_module_inst_t module_inst)
{
    const char *exception;
    //char *wasm_argv[2];
    //wasm_argv[0] = (char *)"wasm_app";
    //wasm_argv[1] = (char *)pixel;

    os_printf("----------------------------------------------\n");
    //os_printf("WARM: call Wasm app, pixel: %s\n", pixel);
    //wasm_application_execute_main(module_inst, 2, wasm_argv);
    wasm_application_execute_main(module_inst, 0, NULL);
    if ((exception = wasm_runtime_get_exception(module_inst)))
        os_printf("%s\n", exception);
    os_printf("----------------------------------------------\n");
    return NULL;
}

void
iwasm_main()
{
    /* setup variables for instantiating and running the wasm module */
    uint8_t *wasm_file_buf = NULL;
    unsigned wasm_file_buf_size = 0;
    wasm_module_t wasm_module = NULL;
    wasm_module_inst_t wasm_module_inst = NULL;
    char error_buf[128];
    void *ret;
    RuntimeInitArgs init_args;

    /* configure memory allocation */
    memset(&init_args, 0, sizeof(RuntimeInitArgs));

    init_args.mem_alloc_type = Alloc_With_Allocator;
    init_args.mem_alloc_option.allocator.malloc_func = (void *)os_malloc;
    init_args.mem_alloc_option.allocator.realloc_func = (void *)os_realloc;
    init_args.mem_alloc_option.allocator.free_func = (void *)os_free;


    os_printf("WAMR: Initialize WASM runtime\n");
    /* initialize runtime environment */
    if (!wasm_runtime_full_init(&init_args)) {
    	os_printf("WAMR: Init runtime failed.\n");
        return;
    }

    NativeSymbol native_symbols[] = {
        {"os_printf", (void*)wasm_os_printf, "($)", NULL},
    };
    wasm_runtime_register_natives("env", native_symbols, sizeof(native_symbols) / sizeof(NativeSymbol));


    os_printf("WAMR: Run wamr with interpreter\n");

    wasm_file_buf = (uint8_t *)wasm_application_file;
    wasm_file_buf_size = sizeof(wasm_application_file);

    /* load WASM module */
    if (!(wasm_module = wasm_runtime_load(wasm_file_buf, wasm_file_buf_size,
                                          error_buf, sizeof(error_buf)))) {
    	os_printf("WAMR: Error in wasm_runtime_load: %s\n", error_buf);
        goto fail1interp;
    }

    os_printf("WAMR: Instantiate WASM runtime\n");
    if (!(wasm_module_inst = wasm_runtime_instantiate(wasm_module,
            		  	  	  	  	  	  384, 	// stack size
										  384,  // heap size
										  error_buf, sizeof(error_buf)))) {
        os_printf("WAMR: Error while instantiating: %s\n", error_buf);
        goto fail2interp;
    }

    os_printf("WAMR: run main() of the application\n");
    ret = app_instance_main(wasm_module_inst);
    assert(!ret);

    /* destroy the module instance */
    os_printf("WAMR: Deinstantiate WASM runtime\n");
    wasm_runtime_deinstantiate(wasm_module_inst);

fail2interp:
    /* unload the module */
    os_printf("WAMR: Unload WASM module\n");
    wasm_runtime_unload(wasm_module);

fail1interp:

    /* destroy runtime environment */
    os_printf("WAMR: Destroy WASM runtime\n");
    wasm_runtime_destroy();

    return;
}

/*=======================================================================*/

int main(void)
{
	os_printf("Starting Wasm-micro-runtime\n");
	iwasm_main();
    return 0;
}
